apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgBlVXyUw3w4Yw/krzvh3hX9gS61Hq/888w0hXtZcphGB10w6PhTU+LSPBEqwWUMe8jbQxUi1kek6H9pkfZA0Tsb/wgOzB2h4UbtpOIqbMG6+gdGPexNHE10rwXM+QMOBlZNhq5hV7odDylG2+og5kzXQazqSzLShti6YnwseRGldPzA9vDf2Khj21mYwoHUEMa7/+eXAtU9OtpLpPcx1i727+tOuLP5rGsUfWK+CVZ/Ge7Pk4qtqdqRgcUz+ty90ApwmRGzaXCT+YO8pm6B9jN/CdyGc+MkW1viKhtSXU6I4qXonUZbTzLfeM+SI3TD37BNWwkfxPcDfir1Y9wiN0jgCJW4BOniC6Qh4ha25GFag6wUwEPIWwInhA93v0Yx216ZnY1Jrs5za6PlHD5Kc+lwoGHJkJfMqnbow9h6vKuhtltW6jUJJTzWwRfVP2FI6J/PMN+euiD168DsikjnXRU10vs57lNGEuatfIaKcCibFAP916H7Ywg7dXB0LrhIutWiZ15ScyUr8SGotYePZGg5hTTrsg+IdqvXq7uyhRSQSuOK8pJYH4T0b12DQsY+ntkdkUKhT3mPzauXN033GwakufixPPiWmabejxe/ZKBJpKZop6747ZdABMVbGUIGzzq3xxo+az1NBg2IVTFbMgmtaV5UsPZoe0QZ8tgMrknurds79TbzdfZzzlJK3tECFoB+QDwuC7o2CU0yTLTZM/vcFG1GNOyQSJpjcRBDzVNquklLXaMpLQ==
    ARTIFACTORY_PASSWORD: AgBoXE+2piguPJYgjmV0pg67jlaco7RbjV+knJB228cRKkPkZ5OxKaIfhJ+l3wykhCwNpWthf2JSu5bU4aOZuwbwlbBJRICas1kDyK7rXPnMfXIitOZFYtn6jUs0XaI/7SdAcVc+4ovfoAd4GYOuEKgkflYYwT7bXoC5XmUK9s6FQsrVDNG1O47HK28NAzN/OQ5BXaIVIavEvSPNF5M+1n0cJUu+ugk/IHiaFDiB5JEsk5AOvk0MHDnPNuk8Vg4LHYtF1EYR38r3J5L5uA1ZnCJChddy939KwM9Lzf+bFMYW+bUL4qLWgdoRrDBF0ySRe/fyzqchjl/dx57qLt0yEE1ggD36Lr9Z3h4pmglEQ0eoa7jJJXceWP2nLbDHyp52bPEpftVGAWsIXksEOcv2gK0c+b1rnJPV9NsIaNb/la78J8EG+9wYjqOWNY9SxMOlDyaqzPzkfCD/4YZR1jR2UJ5VBaaVGLaZPo4yV6e7bgIj3xsJc8oBJFQuV0qAGf4UXjmejPw5cdK72Hu2nGMpacjQ6dMjrBln2Fc+TpF5kmSyc7EZJADHhZvYKFTpBdFKOCobDgljZuZ+kaiZmf5sS5CURAhhJTbZOyJahlfqJFVFlTNirov8/bv3Kl6e40qEyByZc972fS42lBrci6J6s424jBMc1kyVxsTJBGemxN1X7tv5+W5UKj78pl50k9V5eRDfSBydRnShsLzuoXMbcCCq9uvhyw==
    ARTIFACTORY_URL: AgCW2crOf+JMFZhP6AXdEozZOOPF+79NtSHca4fWJ8iQxCfaJ3VeSJyG1BQobM/lTxyl1qWfZXb2Hu/6ilhVtoz9e4hMjzQ5bgDjgx5CJrfiznjU7Od/KQyRMLR/MsUxafAD5cLF9QRhXlUMtTuV9WBse/BLR/HP/qxlSjgIU67Dq+FXaTmPBCSY7UslNRKUFCeL+2CP9cFpuqiBxATD+fppn2i9VrxfP5ekof+ognEDBFW9iGc51PDKC/fPoHM0qTUdjiRJEA8SUxAPJtq+ahZH80okg6o+l2tDy82VbONw4O+zBGiR1dDs+4B7oZQsLhH+jueC2GMbIjqygLJTbiAovVFcG2oKRE5IbB7XJjRY6gN2uxrQsaj7Npy06QkntPj0Zqu/BSC71yJqN8kFIzkDHJlprfwH4rGzWFqSRlUcYM/TFSmhrZAOi8dOuKMKnIgJQcET9RbF2YWJywZZoZbDfXWMEI4z+NTB7ibbfs+unbGPR6yxyLFtdeAF+7XEcyWbKcWNKDVDV1+b6VkdDfMFoniSdqVwFYtTtEuI6qI6FD8SiKlKAd44eDrndLE8YX1dpH6Y42oKYTdB4AEDJbKH/tG3293Qf5+rzuZVfbAlOW+mw4483ooV/jA9V8A46pLxnGMsPLaSNoFawqiPI39PZkvzYFXBMdRExo8iFIrIq5XTNYVyz4cW6PeQlpycqe6tNz8q0x+hu0BcOLuACVDlRgVLhmN7b3zRraWUTgyzmAa7IxDHLVWhMw==
    ARTIFACTORY_USER: AgAemFKRnx0b/KD7YGm3DGGiV75wTknoUq51yzkBY60/QGn3IXz2UAEJdQky8vY3e7GCKrGpWQWig8Hofny9Ky9xZdUOVxp8Vfd7COTM22Lhz7avqW4AELmJmBlB6nZE4Rdq231U6H9cX86DmfoXee9mfsqHoKi1htiwa9GdLSuJmglCJUsLXbiaq+5VF22+T3SFgYZAoD+ELVXzkk4/NCfL017yNhd+DJ3UZRgRXHYuJERvJ5gjgAGxWG8fPOSMmwIStH4kNz8NNPQUsFpEKmbQ/tZx/uKKilJxCyz2tw9bTBBD67DhrDYW2ekwoyttkwGpwc+tf/GlGYBL98304Su/YTTDAl500LX2PG7Ko9cKMWWPugCrO8aPygIkcJ0UidQlym/pcSapqFDOkvL4ABTnTbyy0G/xiwVxyU5redyVMKAOrexZCmM3mVabONkshgSFJQI+eehE8nGX8LEjso+GPAnq7FGUZ6ntSYvqNngIIHCZKPPvELB8MKbygw2UAqBNW0JHjhaI+1b4+JVTlJ9Tbgx61YNdEb1NiLjiisn0LFaIzWBMbv75ebJhJFLokpLIMWmUxvU3wYAgMMMxF2OxsXiR2wvrr8IKYw3COD5ma8PomDKoG8SBx0ng/f3Lw68DuO17XF9Pxa/4zXkk4Fwafp+A/K2NCTh0kjhYQ2DQnyptE8g/FU3lM3ppY8/tIACVNqGH9g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-11-11T22:15:27Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-11-11T22:16:39Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

