apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgBcBZvRYOULa792CWYUSFrtjEN7cFgtqOkWqxfA9604Zw2C+FzPU/2aYZgt3VKZGB79mokC5OrStEvj0vyBLBASFnMS/Sa3bCdTgvR9WeZVkCVaoVIQmYHNHrXfeHw+mFG2UZz3KrPzDOEV6BCp1oB4nOVDyF5QQw0SFqx2yADf2aRJ7YOG6xco2sSYGEso6J7lHE2VnJhRqVHG/QCiqxflzZtWnUa0nbw4T9cdtUaTK/wvqTd94fDbbonH4clnsQmEG9sdsTHD4+nDodaa4veZynLpKxAMWvYEBLwUQyELzBvIOUu/lNSYSnR8nlGlukF+/Ql8e09iQjzAKhGpk49zfebEx++Z5QMSQNnK6QbwdnGLKNea8ttr1Pbmj5C6sSxzOOkcUpWQ7JN7TfqaAEcqdPMYNr1PKPq7xOC038zKqPUpGU2TirqZoltlpnHQCqd4pI2zjQN1pFLHrIFevhzb9oqPmy6eIXFKhP9AtlPEStfF5nLiOH3/iQiNgWJE3eiyDyMcsNV5fSjjOm+1BjXR2tBUr/zkBTxZRSyjmbhwCsnUuW64ID6qjcxfSJ+WwhKLvqnN+Hb2biTVWuVa5mgRo+bnxYt1A2bUlRaj3pIj2za60lumPbe6pLthywP4NTbM29CKlMsVSwgAmkvmysX4S0P+V9jH+ibEk+qtPOCOJppNo44ZpcRxtwHWiiLrbKU3c8GCLjsBXR0dh+ngir0UMQWdpqZ0ezqP7Lb1OEJlMPPxaUtSRw==
    ARTIFACTORY_PASSWORD: AgCTXBWfzxc2yMfl/H7MlA7nyIJZ2jrMVmsGzOyUWEaFWYcisXOOYjJ0+456PgYfLLd9qfRKIJslWjBYshWClqzbfuoyTOE3tZh/RtyA7eAlSb2eZyUSWxWwR4gbaSmr7hyr8QhsxkLIm303faMRVl1Yy08pIu+NKiYNXPf4FZBcK6dO9Bt7xB8CUyXa6CSlga2TVY86Sb1eqcjfkZDz19lqunokts4qdMdh9x3Gw/sNv7WOY0uCM+FVTTLnVFJMUiBtlX+U0cTbRKXAy9UOy/t5SQW6IrZg/NsvsnxuHo4jjveRtV8r4O5TfwVXKhe4iXuzjwYpR5y2D400M9rC7UwMO69fF6ba3gOYubFwJ5CSenxLXhJmFTxZc8sT+0dmfXurfY2HpVg9xb4UC4Gi+9M+kqjw34qQZUzU+ehx8y6NOO7rk4JaWf8uk+ME/YFAnguzbxQ4iq5JjL6KHyqHSN38gtkiUedXXQZaMZ2QLzq9jCs3sLpsv0OcUPSKJ59ZKAjX4IpQ3WmcgKdTsBxCMFH5Zojj5+4LnvCjW2AhIluaXHVgHEjuePJ9yvGvzXc9bl7ygLXznJ+3vi69kfy2HW4VnT5GpyqzPB+x7JuGv066VsR8wY93XyX3MQyuFZL0xtXl4VMOQqhVa/zPM4B5PtC+qyPR9U27QGuiLNotf9LPR8ge4qrP8aceAY1AUX4w0sARWvawgwRBZGyZanJXe0MkyQbX6A==
    ARTIFACTORY_URL: AgA9E2szh/vg4CPB3tgqdxsLHVNumoNET1Hv4WaF1NZY78ZxRKI3mIilIKZQVNKNZNNRJyxKL07lvGwNsnY/j8Fl/pgZAJE3EQGnBcH+SWs0/j0SyIRk9JB3jEqVPyNnkN2GKVRGLdZqa7yVP8BBPabSuGteEMoleFlhuMkj/yUkp3sDInyod9sCOOyENk6cIYnp2THMOjj8b4dfMdfuiNX3FlDFOyfm8sWZmw6LvIAIFkTkivIdfWKSC26ePhnBYdi4IOXfnYIxWCjd1yWLbQ0vf1z9QRArFt/xrjgi11RJ3GsPm0v4WTcyXugEwUzMAW1xFLqHQ0f/xV/A0uYYLqt2A4at+tFnOyErKvnmQzIW31zgHSpbU9RZszUdWZdN0V4de9zTaM1of9bGp+BjgNE3wWwVH1wD7vIBp5nHgxPOB8XSH4GNi5gOla3Ru4dNpPUtjOO/wgaEajVhxNpfNVWIt9rVogaO6g8ZB4Per6Dqoy5V1Sbz1SPjqyhaSZ2Wt8opGOaWpaN6OgYw17bcz1VPMRnumf7+0y/MojYNL9YbvgcDVQGKZUZth7Zqe/shg5jIxcqKaK+DJ35aQDUkJxBHkVCg1LpT+rWjq/LW+kBxLDfQnTKggoN8uI8E/yo1oeyZGaTquf51ijSxQ3PU5OovXvVySIqZhGHpmFrb58xyfuI7KItDq1Drj7rboLaNPmdO34SzUD7CvO3yyttb0CHn3jeIx4hgxRwyZ6wIo/vmh5rggH1sNbWdcw==
    ARTIFACTORY_USER: AgBL11PLTC7/9zX0M0nUQoAnKqW0Fh88ZgDgrtBKs389I+HKURalLDdW3NkKZ0fBLw/eC5SvuiSKd58dE57uQHGojs51Lk7qfDWN4pEGlWHaxeictiDNwHj1zuJ77GCu8uVlgAdiJWpLFW84Xjn7q104lGIrT/BGPuOa3ap0IoomhqZHNpyoqkxiqX9P5ehn/2InGP5CO6O5eIdYcFTgYPiR/iLsh0kYFRvIqML/2CDSF36RpJqkFW060lJ0qUuZj5HJ2ZtB6TFoyhm25Njqvd96MGuYsMzHWsJQnl8vPllP2Cj7nfKMqsqwB6SSmCsn44vyhXsK54erFb9mx7J2fLQtnEuMmOtBNMhbwLErJ04h3p9RTHyJYuRudRzxKB/iJ2sfsJBjwFEdCBt2QPf8H6yzqj4duQVcW5GWW1qO531c8q0+KjcIeXIjcaNY15yBC7F0pAbdL9v5BZ1C5Gos30rf4tuYL89DuChiOOY+PBdP+7f38NtWwSqLWvJFwcN1AgqMfyVgEqbGwuW1Ptnq4vZInfuSkr8nQwsi1sDz5c02XfnXVqpys8k3GH2o/bQhh/fAgZOYel04buy3yz+cvLVCSJcNBygkO/CVq+mDY0RcUArMamrGyVxyzd4l8QjGA7INfZOs+G3h3YvtY4w8r//+daVjFq8BA0SJ322Ac/TLB/HWg+flh8br883pWuRCPgJfKNDH0Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2023-01-10T17:52:09Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2023-01-10T17:53:53Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

